### ISSUE TITLE
To Do!

### ISSUE THREAD

**Issue by alecerf01** [alecerf01/Geezer-Project#1]
- Write javascript for deezer api call and grab needed data
- Write javascript for genius song lyrics api and grab lyrics
- Dynamically add html to fill song container
- Dynamically add html to fill lyric container
- Style Page in external css stylesheet
- add history buttons to specific container
- create modal for when page loads user is alerted to functionality of the webpage
- text that page is fully functional

**Comment by davidklmn** [comment]
All done! :)
